version: "2"

services:
  api:
    container_name: api
    image: server
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - mongo

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./data/mysql:/var/lib/mysql"
    expose:
      - "3306"

  mongo:
    container_name: secondary
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    volumes:
      - "./data/mongodb:/data/db"
    expose:
      - "27017"

  frontend:
    container_name: frontend
    image: client
    build: ./client
    stdin_open: true
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
