version: "2"

services:
  api:
    container_name: api
    image: server
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./data/mysql:/var/lib/mysql"
    expose:
      - "3306"

  frontend:
    container_name: frontend
    image: client
    build: ./client
    stdin_open: true
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
